pipelines:
  - name: bynumberofday
    steps:
      - name: bynumberofday1
        type: Bash
        configuration: 
          nodePool:Bynumberofday
        execution:
          onExecute:
            - printenv
