resources:
  - name: myCronTrigger
    type: CronTrigger
    configuration: 
      interval: "*/2 * * * *"

pipelines: 
  - name: myPipeline
    steps: 
      - name: myScheduledStep
        type: Bash
        configuration: 
          inputResources: 
            - name: myCronTrigger 
