# resources:
#   - name: simple_test1
#     type: GitRepo
#     configuration:
#       gitProvider: vishnurao_github
#       path: vishnurao12/test 
      
# pipelines:
#   - name: pipeline_vishnu
#     steps:
#       - name: node
#         type: Bash
#         configuration:
# #           inputResources:
# #             - name: simple_test1
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions:
#                   - 10.15.3
# #               custom:
# #                 name: drydock/u16node
# #                 tag: master
# #                 autoPull: false
#         execution:
#           onExecute:
#             - nvm list
#             - node --version 
#             - add_run_variables imageTag="master"


#       - name: go
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: node
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - 1.12.6
# #               custom:
# #                 name: drydock/u18go
# #                 tag: master
# #                 autoPull: false
#         execution:
#           onExecute:
#             - source /root/.gvm/scripts/gvm
#             - gvm list
#             - go version
#             - gvm use 1.11.11 
#             - go version
#             - gvm use 1.12.6
#             - go version                
#       - name: cpp
#         type: Bash
#         configuration:
# #           nodePool: vijay_node           
#           inputSteps:
#             - name: go      
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: c
#                 versions:
#                   - 8.0.0
# #               custom:
# #                 name: drydock/u18cpp
# #                 tag: master
# #                 autoPull: true
#         execution:
#           onExecute:
#             - gcc --version
#             - clang --version

resources:
  - name: test1
    type: GitRepo
    configuration:
      gitProvider: vishnurao_github
      path: vishnurao12/test 

pipelines:
  - name: pipeline_vishnu
    steps:
      - name: node
        type: Bash
        configuration:
          inputResources:
            - name: test1
          runtime:
            type: image
            image:
              auto:
                language: nodejs
                versions:
                  - 10.15.3
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 autoPull: false
        
      - name: go
        type: Bash
        configuration:
          inputSteps:
            - name: node
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - 1.12.6
#               custom:
#                 name: drydock/u18go
#                 tag: master
#                 autoPull: false
