resources:
   - name: vmIntegrationResource
     type: VmCluster
     configuration:
       sshKey: sshKey_int
       targets:
         - 0.0.0.1
         - 0.0.0.12
pipelines:
  - name: vr_vmclusters
    steps:
      - name: vr_step
        type: Bash
        configuration:
          inputResources:
            - name: vmIntegrationResource
#           outputResources:
#             - name: tr_int_hook
#             - name: tr_ext_webhook
        execution:
          onExecute:
            - printenv
#             - set_payload tr_ext_webhook "{\"text\":\"Optional text that appears within the attachment\"}"
#             - export tr_ext_hook_2_skipWebhook="true"
#             - apt-get install -y tree
#             - echo "Hello world"
#           #  - echo ""
