resources:
  - name: vishnuCronTrigger
    type: CronTrigger
    configuration: 
      interval: "2 4 6 8 *"
  
  - name: s_image
    type: Image
    configuration:
      registry: docker
#       sourceRepository:    <name of the artifactory repo>   # required if registry is Artifactory
      imageName: shippabledocker/sample_python
      imageTag: latest
      
pipelines: 
  - name: myPipeline
    steps: 
      - name: myScheduledStep
        type: Bash
        configuration: 
          inputResources: 
            - name: s_image
          environmentVariables:
            ENV1: value1
            ENV2: value2  
        execution:
          onExecute:
            - printenv
            - docker images
            - test "$ENV1" == "value1"
            - test "$ENV2" == "value2"
