resources:
  - name: vishnuCronTrigger
    type: CronTrigger
    configuration: 
      interval: "2 4 6 8 *"

pipelines: 
  - name: myPipeline
    steps: 
      - name: myScheduledStep
        type: Bash
        configuration: 
#           inputResources: 
#             - name: vishnuCronTrigger 
          environmentVariables:
            ENV1: value1
            ENV2: value2  
        execution:
          onExecute:
            - printenv
            - docker images
            - test "$ENV1" == "value1"
            - test "$ENV2" == "value2"
