resources:
  - name: test_gitRepo
    type: GitRepo
    configuration:
      path: PIP/automation
      gitProvider: bbs
 
pipelines:
  - name: pipeline2db
    steps:   
      - name: stepB
        type: Bash
        configuration:
          inputResources:
            - name: test_gitRepo
          integrations:
            - name: apiToken
        execution:
          onExecute:
            - printenv
            - pushd $res_test_gitRepo_resourcePath/tests
            - ./test.sh $int_test_gitRepo_api_url $int_test_gitRepo_su_user_Token $int_test_gitRepo_ow_user_Token $int_test_gitRepo_me_user_Token
            - popd
