resources:
   - name: vmIntegrationResource
     type: VmCluster
     configuration:
       sshKey: pem_int
       targets:
         - 0.0.0.1
         - 0.0.0.12
pipelines:
  - name: vr_vmclusters
    steps:
      - name: vr_step
        type: Bash
        configuration:
          inputResources:
            - name: vmIntegrationResource
#           outputResources:
#             - name: tr_int_hook
#             - name: tr_ext_webhook
        execution:
          onExecute:
            - printenv
